# Generated by Django 5.1.3 on 2024-11-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='middlename',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
