# Generated by Django 5.1.3 on 2024-11-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_middlename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='user',
            name='middlename',
        ),
        migrations.AddField(
            model_name='user',
            name='fullname',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
