# Generated by Django 5.1.3 on 2024-11-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_firstname_remove_user_lastname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('storeID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('userID', models.CharField(max_length=100)),
                ('storeName', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='fullname',
        ),
        migrations.AddField(
            model_name='user',
            name='firstname',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AddField(
            model_name='user',
            name='middlename',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
