# Generated by Django 5.1.3 on 2024-11-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_store_remove_user_fullname_user_firstname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lowerUsername',
            field=models.CharField(default='', max_length=25),
        ),
    ]
