# Generated by Django 5.1.3 on 2024-12-11 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_user_lowerusername"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
