# Generated by Django 5.1.3 on 2024-11-14 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_expirydate_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productDescription',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
