# Generated by Django 5.1.3 on 2024-11-24 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_productdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
