# Generated by Django 5.1.3 on 2024-11-25 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('productID', models.CharField(max_length=1000)),
                ('userInfo', models.CharField(max_length=25, null=True)),
                ('quantuty', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
