# Generated by Django 5.1.3 on 2024-11-26 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='productImage',
        ),
        migrations.AlterField(
            model_name='product',
            name='productDescription',
            field=models.TextField(),
        ),
    ]
