# Generated by Django 5.1.3 on 2024-11-27 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_img_product_productimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantuty',
            new_name='quantity',
        ),
        migrations.AddField(
            model_name='product',
            name='availability',
            field=models.IntegerField(default=0),
        ),
    ]
