# Generated by Django 5.1.3 on 2024-11-27 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_rename_quantuty_order_quantity_product_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='availability',
            field=models.IntegerField(),
        ),
    ]
