# Generated by Django 5.1.3 on 2024-11-27 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_product_availability'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='availability',
            new_name='avail',
        ),
        migrations.AddField(
            model_name='product',
            name='stocks',
            field=models.IntegerField(default=0),
        ),
    ]
