# Generated by Django 5.1.3 on 2024-11-27 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_rename_availability_product_avail_product_stocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productStore',
            field=models.CharField(default='', max_length=100),
        ),
    ]
