# Generated by Django 5.1.3 on 2024-11-28 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_product_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('orderID', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('productID', models.CharField(max_length=1000)),
                ('userInfo', models.CharField(max_length=25, null=True)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
