# Generated by Django 5.1.3 on 2024-11-28 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_alter_cart_quantity_alter_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='orderID',
            new_name='cartID',
        ),
    ]
