# Generated by Django 5.1.3 on 2024-11-28 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0018_rename_orderid_cart_cartid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='productID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cart',
            name='userInfo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
