# Generated by Django 5.1.3 on 2024-11-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0019_alter_cart_productid_alter_cart_userinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='storeID',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='storeID',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='productID',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='userInfo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
