# Generated by Django 5.1.3 on 2024-12-01 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0021_order_location_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='storeID',
        ),
    ]
