# Generated by Django 5.1.3 on 2024-12-02 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_remove_order_storeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='storeID',
            field=models.IntegerField(default=1),
        ),
    ]
